# Generated by Django 4.2.7 on 2023-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_deck', models.CharField(max_length=100)),
                ('opp_deck', models.CharField(max_length=100)),
                ('season', models.CharField(blank=True, max_length=100)),
                ('tournament', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('started_play', models.BooleanField(blank=True, null=True)),
                ('result_g1', models.CharField(max_length=1)),
                ('result_g2', models.CharField(max_length=1)),
                ('result_g3', models.CharField(blank=True, max_length=1)),
                ('mulligans_g1', models.PositiveIntegerField(blank=True)),
                ('mulligans_g2', models.PositiveIntegerField(blank=True)),
                ('mulligans_g3', models.PositiveIntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
