# Generated by Django 4.2.7 on 2023-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mulligans_g1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mulligans_g2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mulligans_g3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
