# Generated by Django 5.0 on 2023-12-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtgtracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='games_played_against',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='games_played_with',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='games_won_against',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='games_won_with',
        ),
        migrations.RemoveField(
            model_name='game',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='game',
            name='games_won',
        ),
    ]
