# Generated by Django 5.0 on 2023-12-05 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgtracker', '0002_remove_deck_games_played_against_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='mulligans_g1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='mulligans_g2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='mulligans_g3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='result_g1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='result_g2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='result_g3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='started_play',
        ),
        migrations.AlterField(
            model_name='game',
            name='opp_deck',
            field=models.ManyToManyField(related_name='games_against', to='mtgtracker.deck'),
        ),
        migrations.AlterField(
            model_name='game',
            name='your_deck',
            field=models.ManyToManyField(related_name='games_with', to='mtgtracker.deck'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Lose'), ('D', 'Draw')], max_length=1)),
                ('mulligans', models.PositiveIntegerField(blank=True, null=True)),
                ('started_play', models.BooleanField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='mtgtracker.game')),
            ],
        ),
    ]
