# Generated by Django 5.0 on 2023-12-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgtracker', '0003_remove_game_mulligans_g1_remove_game_mulligans_g2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_first_match',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
