# Generated by Django 5.0 on 2023-12-06 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgtracker', '0006_remove_game_opp_deck_remove_game_your_deck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='opp_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_against', to='mtgtracker.deck'),
        ),
        migrations.AlterField(
            model_name='game',
            name='your_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_with', to='mtgtracker.deck'),
        ),
    ]
